version: "3"

tasks:
  default: # mimics default behavior but skipping non-zero exit
    desc: "Default task to list all tasks"
    cmds:
      - task --list-all

  tests:unit:
    desc: "Run unit tests"
    cmds:
      - pytest tests/unit --cov src --cov-fail-under=0

  tests:check-code-coverage:
    desc: "Run code coverage checks and create reports"
    cmds:
      - ./scripts/code-coverage-report.sh

  tests:code-coverage:
    desc: "Run code coverage checks (simulating the CI setup locally)"
    cmds:
      - |
        task tests:unit
        task tests:check-code-coverage
